name: traefik_modsec
services:
  traefik:
    image: docker.io/library/traefik:latest
    ports:
      - 8080:8080
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --experimental.plugins.modsec.modulename=github.com/kenshaw/traefik-modsec
      - --experimental.plugins.modsec.version=v0.1.0
      - --providers.docker=true
      - --entrypoints.http.address=:80
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.modsec.plugin.modsec.jail.enabled=true
      # use traefiks built-in maxRequestBodyBytes middleware - there's no need for us to bake this ourselves
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=1048576

  modsec:
    image: docker.io/owasp/modsecurity-crs:nginx
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - BACKEND=http://dummy
      - REPORTING_LEVEL=2
      - MODSEC_AUDIT_LOG_FORMAT=JSON
      - MODSEC_RULE_ENGINE=On

  website-with-modsec:
    image: docker.io/traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.website-with-modsec.rule=PathPrefix(`/website`)
      - traefik.http.routers.website-with-modsec.middlewares=modsec@docker

  website:
    image: docker.io/traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=PathPrefix(`/bypass`)
